//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MMK;

[assembly: RegisterDocumentType(GalleryPage.CLASS_NAME, typeof(GalleryPage))]

namespace CMS.DocumentEngine.Types.MMK
{
	/// <summary>
	/// Represents a content item of type GalleryPage.
	/// </summary>
	public partial class GalleryPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MMK.GalleryPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with GalleryPage fields.
		/// </summary>
		private readonly GalleryPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with GalleryPage fields.
		/// </summary>
		[RegisterProperty]
		public GalleryPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with GalleryPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GalleryPageFields : AbstractHierarchicalObject<GalleryPageFields>
		{
			/// <summary>
			/// The content item of type GalleryPage that is a target of the extended API.
			/// </summary>
			private readonly GalleryPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GalleryPageFields" /> class with the specified content item of type GalleryPage.
			/// </summary>
			/// <param name="instance">The content item of type GalleryPage that is a target of the extended API.</param>
			public GalleryPageFields(GalleryPage instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="GalleryPage" /> class.
		/// </summary>
		public GalleryPage() : base(CLASS_NAME)
		{
			mFields = new GalleryPageFields(this);
		}

		#endregion
	}
}