//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MMK;

[assembly: RegisterDocumentType(HomePage.CLASS_NAME, typeof(HomePage))]

namespace CMS.DocumentEngine.Types.MMK
{
	/// <summary>
	/// Represents a content item of type HomePage.
	/// </summary>
	public partial class HomePage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MMK.HomePage";


		/// <summary>
		/// The instance of the class that provides extended API for working with HomePage fields.
		/// </summary>
		private readonly HomePageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with HomePage fields.
		/// </summary>
		[RegisterProperty]
		public HomePageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with HomePage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HomePageFields : AbstractHierarchicalObject<HomePageFields>
		{
			/// <summary>
			/// The content item of type HomePage that is a target of the extended API.
			/// </summary>
			private readonly HomePage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HomePageFields" /> class with the specified content item of type HomePage.
			/// </summary>
			/// <param name="instance">The content item of type HomePage that is a target of the extended API.</param>
			public HomePageFields(HomePage instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="HomePage" /> class.
		/// </summary>
		public HomePage() : base(CLASS_NAME)
		{
			mFields = new HomePageFields(this);
		}

		#endregion
	}
}