//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MMK;

[assembly: RegisterDocumentType(Calendar.CLASS_NAME, typeof(Calendar))]

namespace CMS.DocumentEngine.Types.MMK
{
	/// <summary>
	/// Represents a content item of type Calendar.
	/// </summary>
	public partial class Calendar : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MMK.Calendar";


		/// <summary>
		/// The instance of the class that provides extended API for working with Calendar fields.
		/// </summary>
		private readonly CalendarFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with Calendar fields.
		/// </summary>
		[RegisterProperty]
		public CalendarFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Calendar fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CalendarFields : AbstractHierarchicalObject<CalendarFields>
		{
			/// <summary>
			/// The content item of type Calendar that is a target of the extended API.
			/// </summary>
			private readonly Calendar mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CalendarFields" /> class with the specified content item of type Calendar.
			/// </summary>
			/// <param name="instance">The content item of type Calendar that is a target of the extended API.</param>
			public CalendarFields(Calendar instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Calendar" /> class.
		/// </summary>
		public Calendar() : base(CLASS_NAME)
		{
			mFields = new CalendarFields(this);
		}

		#endregion
	}
}