//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MMK;

[assembly: RegisterDocumentType(Team.CLASS_NAME, typeof(Team))]

namespace CMS.DocumentEngine.Types.MMK
{
	/// <summary>
	/// Represents a content item of type Team.
	/// </summary>
	public partial class Team : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MMK.Team";


		/// <summary>
		/// The instance of the class that provides extended API for working with Team fields.
		/// </summary>
		private readonly TeamFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TeamID.
		/// </summary>
		[DatabaseIDField]
		public int TeamID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TeamID"), 0);
			}
			set
			{
				SetValue("TeamID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Details.
		/// </summary>
		[DatabaseField]
		public string Details
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Details"), @"");
			}
			set
			{
				SetValue("Details", value);
			}
		}


		/// <summary>
		/// Photo.
		/// </summary>
		[DatabaseField]
		public string Photo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Photo"), @"");
			}
			set
			{
				SetValue("Photo", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Team fields.
		/// </summary>
		[RegisterProperty]
		public TeamFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Team fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TeamFields : AbstractHierarchicalObject<TeamFields>
		{
			/// <summary>
			/// The content item of type Team that is a target of the extended API.
			/// </summary>
			private readonly Team mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TeamFields" /> class with the specified content item of type Team.
			/// </summary>
			/// <param name="instance">The content item of type Team that is a target of the extended API.</param>
			public TeamFields(Team instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TeamID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TeamID;
				}
				set
				{
					mInstance.TeamID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Details.
			/// </summary>
			public string Details
			{
				get
				{
					return mInstance.Details;
				}
				set
				{
					mInstance.Details = value;
				}
			}


			/// <summary>
			/// Photo.
			/// </summary>
			public string Photo
			{
				get
				{
					return mInstance.Photo;
				}
				set
				{
					mInstance.Photo = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Team" /> class.
		/// </summary>
		public Team() : base(CLASS_NAME)
		{
			mFields = new TeamFields(this);
		}

		#endregion
	}
}