//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MMK;

[assembly: RegisterDocumentType(Event.CLASS_NAME, typeof(Event))]

namespace CMS.DocumentEngine.Types.MMK
{
	/// <summary>
	/// Represents a content item of type Event.
	/// </summary>
	public partial class Event : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MMK.Event";


		/// <summary>
		/// The instance of the class that provides extended API for working with Event fields.
		/// </summary>
		private readonly EventFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// EventID.
		/// </summary>
		[DatabaseIDField]
		public int EventID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("EventID"), 0);
			}
			set
			{
				SetValue("EventID", value);
			}
		}


		/// <summary>
		/// Event Title.
		/// </summary>
		[DatabaseField]
		public string EventTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EventTitle"), @"");
			}
			set
			{
				SetValue("EventTitle", value);
			}
		}


		/// <summary>
		/// Event Details.
		/// </summary>
		[DatabaseField]
		public string EventDetails
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EventDetails"), @"");
			}
			set
			{
				SetValue("EventDetails", value);
			}
		}


		/// <summary>
		/// Start Date.
		/// </summary>
		[DatabaseField]
		public DateTime StartDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("StartDate"), ValidationHelper.GetDateTime("##TODAY##", DateTimeHelper.ZERO_TIME));
			}
			set
			{
				SetValue("StartDate", value);
			}
		}


		/// <summary>
		/// End Date.
		/// </summary>
		[DatabaseField]
		public DateTime EndDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("EndDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("EndDate", value);
			}
		}


		/// <summary>
		/// Days.
		/// </summary>
		[DatabaseField]
		public string Days
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Days"), @"");
			}
			set
			{
				SetValue("Days", value);
			}
		}


		/// <summary>
		/// Link.
		/// </summary>
		[DatabaseField]
		public string Link
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Link"), @"");
			}
			set
			{
				SetValue("Link", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string Image
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Image"), @"");
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Event fields.
		/// </summary>
		[RegisterProperty]
		public EventFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Event fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class EventFields : AbstractHierarchicalObject<EventFields>
		{
			/// <summary>
			/// The content item of type Event that is a target of the extended API.
			/// </summary>
			private readonly Event mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="EventFields" /> class with the specified content item of type Event.
			/// </summary>
			/// <param name="instance">The content item of type Event that is a target of the extended API.</param>
			public EventFields(Event instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// EventID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.EventID;
				}
				set
				{
					mInstance.EventID = value;
				}
			}


			/// <summary>
			/// Event Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.EventTitle;
				}
				set
				{
					mInstance.EventTitle = value;
				}
			}


			/// <summary>
			/// Event Details.
			/// </summary>
			public string Details
			{
				get
				{
					return mInstance.EventDetails;
				}
				set
				{
					mInstance.EventDetails = value;
				}
			}


			/// <summary>
			/// Start Date.
			/// </summary>
			public DateTime StartDate
			{
				get
				{
					return mInstance.StartDate;
				}
				set
				{
					mInstance.StartDate = value;
				}
			}


			/// <summary>
			/// End Date.
			/// </summary>
			public DateTime EndDate
			{
				get
				{
					return mInstance.EndDate;
				}
				set
				{
					mInstance.EndDate = value;
				}
			}


			/// <summary>
			/// Days.
			/// </summary>
			public string Days
			{
				get
				{
					return mInstance.Days;
				}
				set
				{
					mInstance.Days = value;
				}
			}


			/// <summary>
			/// Link.
			/// </summary>
			public string Link
			{
				get
				{
					return mInstance.Link;
				}
				set
				{
					mInstance.Link = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.Image;
				}
				set
				{
					mInstance.Image = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Event" /> class.
		/// </summary>
		public Event() : base(CLASS_NAME)
		{
			mFields = new EventFields(this);
		}

		#endregion
	}
}